// Code generated by go-swagger; DO NOT EDIT.

package v2alpha

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Toolchain toolchain
//
// swagger:model Toolchain
type Toolchain struct {

	// name
	Name string `json:"name,omitempty" yaml:"name,omitempty"`

	// version
	Version string `json:"version,omitempty" yaml:"version,omitempty"`
}

// Validate validates this toolchain
func (m *Toolchain) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this toolchain based on context it is used
func (m *Toolchain) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Toolchain) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Toolchain) UnmarshalBinary(b []byte) error {
	var res Toolchain
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
